name: auto-testing
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_tokens: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python test.py

          echo '## MODEL METRICS' > report.md
          cat metrics.txt >> report.md

          cml-send-comment report.md